class_name Album
## Mahalle albümü: oyunda ilk kez yaşanan güzel anlar birer fotoğraf kartı
## olarak saklanır. Her kartın arkasında Fatma Teyze'nin bir notu var.
## "hint": kart açılmadan önce ne yapılacağını söyleyen ipucu.

const CARDS := [
	{"id": "ilk_is", "title": "İlk İş", "icon": "domates", "color": "#e8735a",
		"hint": "Fatma Teyze'nin ilk işini yap.",
		"note": "Mahalleye geldiğin ilk gün bana iki domates almıştın. O gün anladım, sen bizden birisin."},
	{"id": "pazar", "title": "Pazar Günü", "icon": "file", "color": "#4f9a4a",
		"hint": "Pazardan alışveriş işini bitir.",
		"note": "Manav Hasan bile şaşırdı, ne güzel seçmişsin domatesleri. Pazarın tozunu yuttun artık!"},
	{"id": "sutlu", "title": "Sütlü'nün Maması", "icon": "cat", "color": "#e8b33a",
		"hint": "Sütlü'ye mama ver.",
		"note": "Sütlü kimseye yaklaşmazdı. Sen mamasını verdin, peşine takıldı. Kediler iyi insanı bilir."},
	{"id": "sutlu7", "title": "Benim Kedim", "icon": "cat", "color": "#d98c3a",
		"hint": "Sütlü'yü yedi gün besle.",
		"note": "Bir hafta aksatmadın. Sütlü artık senin kedin, kapının önünde seni bekliyor."},
	{"id": "dost", "title": "İlk Dostluk", "icon": "heart", "color": "#d6577a",
		"hint": "Bir komşunun ricasını yap.",
		"note": "Komşuluk bir kalple başlar. Sen ilk kalbini kazandın, gerisi kendiliğinden gelir."},
	{"id": "herkes", "title": "Herkes Tanıdı", "icon": "heart", "color": "#b5468a",
		"hint": "Bütün komşularla tanış.",
		"note": "Artık mahallede seni tanımayan kalmadı. Bayramda kapı kapı gezsen bitmez!"},
	{"id": "can_dost", "title": "Can Dostu", "icon": "heart", "color": "#c8412f",
		"hint": "Bir komşuyla dostluğu tamamla.",
		"note": "Can dostu kolay bulunmaz evladım. Sen buldun, kıymetini bil."},
	{"id": "ekim", "title": "İlk Fide", "icon": "havuc", "color": "#7a9a3a",
		"hint": "Bostana bir şey ek.",
		"note": "Toprağa ilk tohumu bıraktın. Toprak sabırlıdır, sen de sabırlı ol."},
	{"id": "hasat", "title": "İlk Hasat", "icon": "domates", "color": "#c8412f",
		"hint": "Bostandan ürün topla.",
		"note": "Kendi ektiğini kendin topladın. Dünyanın en tatlı domatesi kendi bostanının domatesidir."},
	{"id": "hediye", "title": "Bostandan Hediye", "icon": "kese", "color": "#a0452e",
		"hint": "Bostan ürününü bir komşuya hediye et.",
		"note": "Komşuya eli boş gidilmez. Senin götürdüğün hediyeyi bütün sokak konuştu."},
	{"id": "tavla", "title": "Mars!", "icon": "yildiz", "color": "#5c3a26",
		"hint": "Ahmet Amca'yı tavlada yen.",
		"note": "Ahmet Amca kahvede herkese anlatıyor: Beni bir genç yendi diye. Hem kızıyor hem gururlanıyor."},
	{"id": "cay", "title": "Tavşan Kanı", "icon": "cay", "color": "#a8322a",
		"hint": "Filiz Teyze'yle çay demle.",
		"note": "Çayın kıvamını tutturmak her babayiğidin harcı değil. Filiz'in yüzü güldü."},
	{"id": "balik", "title": "Göl Kenarı", "icon": "balik", "color": "#3e8fb0",
		"hint": "Ahmet Amca'yla balık tut.",
		"note": "Ahmet Amca o gün balıktan çok sohbete daldı. Akşam tavada kızarttık, mis gibi."},
	{"id": "orgu", "title": "İlk Atkı", "icon": "orgu", "color": "#d6577a",
		"hint": "Miyase Teyze'yle örgü ör.",
		"note": "Biraz eğri büğrü oldu ama olsun, el emeği göz nuru. Kışın boynunu sıcacık tutar."},
	{"id": "manti", "title": "Mantı Günü", "icon": "manti", "color": "#d9a05b",
		"hint": "Hülya Teyze'yle mantı yap.",
		"note": "Kaşığa dört tane sığacak kadar küçük yapmışsın! Hülya'nın gözü yaşardı, annesini hatırladı."},
	{"id": "firin", "title": "Fırının Işığı", "icon": "firin", "color": "#c8553a",
		"hint": "Mehmet Usta'nın fırınını yeniden aç.",
		"note": "O sabah bütün mahalle fırının önündeydi. Mehmet'in gözleri doldu, ben de tutamadım kendimi. Mahalle yeniden nefes aldı."},
	{"id": "simit", "title": "Sıcak Simit", "icon": "simit", "color": "#c8873a",
		"hint": "Fırından aldığın simidi bir komşuna götür.",
		"note": "Sabah sabah kapıya sıcak simit gelince insanın içi ısınıyor. Komşuluk dediğin böyle olur."},
	{"id": "yuzuk", "title": "Kayıp Yüzük", "icon": "yuzuk", "color": "#c9a02a",
		"hint": "Elif'in kayıp yüzüğünü bul.",
		"note": "Yüzük bulununca Elif boynuma sarıldı, bir daha bırakmadı. Gözün keskinmiş evladım!"},
	{"id": "dugun", "title": "Mahallede Düğün", "icon": "pasta", "color": "#d6577a",
		"hint": "Elif'in düğününü mahallede yap.",
		"note": "Ahmet'in davulu, Mehmet'in pastası, Miyase'nin kına örtüsü... Bütün mahalle bir halayda el ele tutuştu. Ömrüme ömür kattın."},
	{"id": "ev", "title": "Yuvam", "icon": "ev", "color": "#8e5bb5",
		"hint": "Evine bir eşya koy.",
		"note": "Bir ev eşyayla değil, içindeki muhabbetle ev olur. Ama güzel bir kilim de fena olmaz hani!"},
	{"id": "ev_dolu", "title": "Dört Dörtlük Ev", "icon": "ev", "color": "#5b6fb5",
		"hint": "Evinin bütün köşelerini doldur.",
		"note": "Evin öyle güzel oldu ki misafir gelse kalkıp gitmez. Çayı demle, kapıyı aç!"},
	{"id": "dukkan", "title": "Dükkandan Hediye", "icon": "zil", "color": "#c97a2a",
		"hint": "Dükkandan bir şey al.",
		"note": "Biriktirdiğin kurabiyeleri harcamayı da bildin. Akıllı evlat!"},
	{"id": "sus", "title": "Mahalleye Süs", "icon": "tree", "color": "#4f8a5b",
		"hint": "Mahalleye bir süs al.",
		"note": "Mahallemiz senin sayende güzelleşti. Gelen geçen dönüp bakıyor."},
	{"id": "sabah", "title": "Erkenci", "icon": "gunes", "color": "#f2a93a",
		"hint": "Sabah erkenden mahalleye gel.",
		"note": "Sabah ezanıyla kalkan, kuşlarla uyanan bereketli olur. Simitler daha sıcakken geldin."},
	{"id": "gece", "title": "Ay Işığında", "icon": "ay", "color": "#3a4a7a",
		"hint": "Gece mahallede dolaş.",
		"note": "Sokak lambaları yanınca mahalle başka güzel oluyor. Ama geç kalma, üşütürsün!"},
	{"id": "yagmur", "title": "Yağmur Yağıyor", "icon": "yagmur", "color": "#6a8fb0",
		"hint": "Yağmurlu bir günde gel.",
		"note": "Yağmur yağdı, toprak kokusu sardı mahalleyi. Şemsiyeni unutmamışsın, aferin."},
	{"id": "hafta", "title": "Bir Hafta", "icon": "takvim", "color": "#c8412f",
		"hint": "Yedi gün üst üste gel.",
		"note": "Yedi gün hiç aksatmadın. Seni her sabah bekler oldum evladım."},
	{"id": "seviye5", "title": "Mahallenin Gözdesi", "icon": "yildiz", "color": "#e0a92a",
		"hint": "5. seviyeye ulaş.",
		"note": "Artık mahallenin gözdesi sensin. Kim bir iş isteyecek olsa önce senin adın geçiyor."},
	{"id": "kurabiye", "title": "Kurabiye Kavanozu", "icon": "kurabiye", "color": "#b07a3a",
		"hint": "100 kurabiye biriktir.",
		"note": "Kavanoz ağzına kadar doldu! Hepsini bir oturuşta yeme ama, dişlerin bozulur."},
]


static func get_card(id: String) -> Dictionary:
	for c in CARDS:
		if c["id"] == id:
			return c
	return {}
